parser: 'babel-eslint'
env:
  es6: true
  node: true
  jest: true
plugins:
  - react
extends: 
  - 'eslint-config-airbnb'
  - 'plugin:react/recommended'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-console:
    - off
  no-unused-vars:
    - error
    - vars: all
      args: none
  no-use-before-define:
    - off
  class-methods-use-this:
    - off
  comma-dangle:
    - off
  arrow-parens:
    - off
  no-underscore-dangle:
    - off
  no-restricted-syntax:
    - off
  template-curly-spacing:
    - off
  prefer-destructuring:
    - off
  import/prefer-default-export:
    - off
  import/extensions:
    - off
  lines-between-class-members:
    - off
  no-trailing-spaces:
    - 2
  no-multiple-empty-lines:
    - off
  operator-linebreak:
    - off
  import/no-useless-path-segments:
    - off
  react/display-name:
    - off
  react/prop-types:
    - off
  react/jsx-filename-extension:
    - 1
    - extensions:
      - ".js"
  react/jsx-max-props-per-line:
    - off
  react/forbid-prop-types:
    - off
  react/sort-comp:
    - off

globals:
  window: false
  fetch: false
  Headers: false
  escape: false
