version: '3'
services:
  caddy:
    image: abiosoft/caddy
    links:
      - mdwiki
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - "./Caddyfile:/etc/Caddyfile"
      - "$HOME/.caddy:/root.caddy"
      - "/var/log:/var/log"

  mdwiki:
    image: janbaer/mdwiki:latest
    environment:
      - PORT=3000
      - NODE_ENV=production
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    ports:
      - 3000:3000
    restart: always
